### ISSUE TITLE
[US-1]Login

### ISSUE THREAD

**Issue by Tim-Pet** [Tim-Pet/capstone-project#1]
# Value statement

As a user
I need to log in to Spotify
so that I get access to the app

# Description
![Login-3](https://user-images.githubusercontent.com/73392170/120802637-f42c7600-c542-11eb-8ef8-412e901b2184.png)

# Acceptance criteria

- [x] The user gets redirect to the Spotify auth upon clicking the login button
- [x] Afterwards the user gets automatically redirected to the Criteria Screen
- [x] Some User Data are shown in the Main Screen upon logging in

# Tasks

- [x] Create Login & Recommendation component
- [x] Set up conditional rendering 
- [x] Catch the token
- [x] Fetch Data

### Login
- [x] Register & Setup App at Spotify
- [x] Get the scopes (permissions) needed
- [x] Build loginUrl

### App
- [x] Get token from Url
- [x] Pass the token to Spotify
- [x] Fetch Data

### Criteria
- [x] Render some Data (username)

# Complexity

high
