### ISSUE TITLE
Add Backend & History

### ISSUE THREAD

**Issue by Tim-Pet** [Tim-Pet/capstone-project#11]
# Value statement

As a developer
I need to manage the created playlists outside of Spotify
so that I can provide persistent data to the customer

# Description (Text, Scribble, Wireframe, Design)

# Acceptance criteria

- [x] Have a running MongoDB
- [x] Provide basic routes to manage data
- [x] BE setup to save the playlists individually per customer

# Tasks

- [x] Setup MongoDB
- [x] Setup packages needed & restructure code
- [x] Build server.js
- [x] Add Routes to save Playlists
- [x] Create User if not existent yet
- [x] Sync Spotify & Backend Data
- [x] Update User locally & in DB upon creating a new Playlist
- [x] Conditionally render playlists or songs
- [x] Add Switch for conditionally rendering

# Complexity

medium
