### ISSUE TITLE
Add History FE 

### ISSUE THREAD

**Issue by Tim-Pet** [Tim-Pet/capstone-project#14]
# Value statement

As a user
I need to see my last saved Playlists
so that I see earlier recommendations

# Description (Text, Scribble, Wireframe, Design)
![Playlist history](https://user-images.githubusercontent.com/73392170/123398857-45f57880-d5a4-11eb-9702-30e67465388b.png)

# Acceptance criteria

- [x] Fixed switch between Current recommendations & History
- [x] Highlighting of currently selected 'Tab'

# Tasks

- [x] Implement Switch
- [x] Fetch History from MongoDB
- [x] Basic style Playlistentries

# Complexity

low
