### ISSUE TITLE
Playlisthistory detailed view

### ISSUE THREAD

**Issue by Tim-Pet** [Tim-Pet/capstone-project#15]
# Value statement

As a user
I need to peek into old Playlist
so that I can remember which Playlist I really liked and resave it if needed

# Description (Text, Scribble, Wireframe, Design)
![Playlist history detailed](https://user-images.githubusercontent.com/73392170/123400533-28291300-d5a6-11eb-9728-3503472558c0.png)

# Acceptance criteria

- [ ] On Click an overlay opens and displays the songs inside the Playlist
- [ ] The list is scrollable
- [ ] The title is displayed at the top
- [ ] On click of the cross in the upper right corner of the overlay the overlay closes
- [ ] The Background gets slightly blurred upon opening the Overlay

# Tasks

- [ ] Build the Overlay (Good starting point is the scrollSelector)
- [ ] Add route to BE
- [ ] Fetch Songs of the selected Playlist
- [ ] Connect onClick, states & Overlay

# Complexity
medium
