### ISSUE TITLE
[US-2]Recommendations

### ISSUE THREAD

**Issue by Tim-Pet** [Tim-Pet/capstone-project#2]
# Value statement

As a user
I need to change the recommendation criteria
so that I can customise my generated playlist

# Description
![Criteria selector-2](https://user-images.githubusercontent.com/73392170/120802264-8718e080-c542-11eb-9671-73077124e571.png)

# Acceptance criteria

- [x] The base genre is classical 
- [x] The user can select the(targeted) liveness on a scale from 0-1 with a range slider
- [x] The user submits his entry upon clicking the get recommendations button & gets redirected to the created playlist
- [x] Based on the input the user receives up to 10 songs (at least one)
- [x] The user can return to the Select Page (previously Main Page) by clicking the "back"-button

# Tasks

- [x] Add Form for sample criteria
- [x] Build url based on Input
- [x] Fetch API Data with custom url
- [x] Add Recommendation component
- [x] Add Route
- [x] Display received songs
- [x] Add a return Button

# Complexity

medium

**Comment by badabam** [comment]
How do I get to this screen? Please update the scribbles/acceptance criteria.
