### ISSUE TITLE
[US-3]Create Playlist

### ISSUE THREAD

**Issue by Tim-Pet** [Tim-Pet/capstone-project#3]
# Value statement

As a user
I need to save the Playlist to my Spotify Account
so that I can access it later

# Description

![Create Playlist-5](https://user-images.githubusercontent.com/73392170/120804436-ef68c180-c544-11eb-9905-afcc8a78a788.png)

# Acceptance criteria

- [x] The button create Playlist redirects to the create Playlist page
- [x] The user submits a playlist to Spotify with the entered title, description and recommendations by clicking the "create playlist" button
- [x] The Button is disabled until the following criteria is met: The title has to have a value which can contain anything but nothing & whitespaces only
- [x] Upon entering valid values & submitting the button greys out and shows a success icon (tick) and renders new text "Playlist Created"
- [x] The back button returns to the recommendation page
- [x] If the communication with the Spotify API throws an error the error prompt "Service is currently unavailable. Please try again later" should show up and the button text doesn't change
- [x] The error prompt disappears after 10 seconds

# Tasks

- [x] Add create playlist Page 
- [x] Add Form component
- [x] Set a filter for invalid entries
- [x] Build the "Create playlist" API call with title, description & songs [Spotify docs](https://developer.spotify.com/documentation/web-api/reference/#endpoint-create-playlist) [Web-Api docs](https://jmperezperez.com/spotify-web-api-js/?q=cre#src-spotify-web-api.js-constr.prototype.createplaylist)
- [x] Take the Playlist ID from the resp
- [x] Add all tracks to the created Playlist [Spotify docs](https://developer.spotify.com/documentation/web-api/reference/#endpoint-add-tracks-to-playlist) [Web API](https://jmperezperez.com/spotify-web-api-js/?q=add#src-spotify-web-api.js-constr.prototype.addtrackstoplaylist)
- [x] Render error message upon submit with invalid values
- [x] Rerender button text & icon upon submit with valid values

# Complexity

medium

**Comment by badabam** [comment]
When is the error shown? On blur? On button click? Could you instead disable the button until everything is filled out (so no error message is needed for this?).
You also need a place (and acceptance criteria) to show other errors that can occur (server not available, some other errors from spotify)
