### ISSUE TITLE
[US-4]Criteria presets

### ISSUE THREAD

**Issue by Tim-Pet** [Tim-Pet/capstone-project#4]
# Value statement

As a user
I need to select a preset based on my mood
so that I decide easier upon the criteria and not be overwhelmed by the possibilities

# Description

![Mood selector-2](https://user-images.githubusercontent.com/73392170/120804729-48d0f080-c545-11eb-9d31-c435ae42ccd9.png)

# Acceptance criteria

- [x] At least 10 different moods to choose from ([Emotion List](https://englishstudyhere.com/vocabulary/list-of-emotions/))<br>[Upset, Lost, Sad, Frustrated, Dynamic, Powerful, Ambitious, Joyful, Charmed, Focused, Renewed, ...]
- [x] Every mood has a different criteria preset 
- [x] Based on the mood a different playlist is created
- [x] The mood selector is a spin/scroll selector and can get dragged to select a preset/mood

# Tasks

- [x] Create preset objects
- [x] Connect selection of the current mood with the submit event
- [x] Create a custom spin-selector

# Complexity

high

**Comment by badabam** [comment]
Your scribble looks like you don't need a draggable list until you reach like >10 presets – they all could fit into the screen without scrolling.
