### ISSUE TITLE
UX

### ISSUE THREAD

**Issue by Tim-Pet** [Tim-Pet/capstone-project#9]
# Value statement

As a user
I need to receive feedback for my actions
so that I have a nice experience

# Description (Text, Scribble, Wireframe, Design)

# Acceptance criteria

- [ ] Create Playlist Button renders a Icon upon successful submit (opt. redirect back after 1s)
- [ ] Loading spinner for requests
- [ ] Hover effects
- [ ] OnClick animations
- [ ] Style Selectors (Draggable spinner & Genre selector)

# Tasks

- [] Task 1

# Complexity

(low, medium, high)
